/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bgi_flexlab_dpgt_jointcalling_VariantSiteFinder */

#ifndef _Included_org_bgi_flexlab_dpgt_jointcalling_VariantSiteFinder
#define _Included_org_bgi_flexlab_dpgt_jointcalling_VariantSiteFinder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bgi_flexlab_dpgt_jointcalling_VariantSiteFinder
 * Method:    FindVariantSite
 * Signature: ([Ljava/lang/String;Ljava/lang/String;JJ)[B
 */
JNIEXPORT void JNICALL Java_org_bgi_flexlab_dpgt_jointcalling_VariantSiteFinder_FindVariantSite
  (JNIEnv *, jobject, jobjectArray, jstring, jstring, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif