/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bgi_flexlab_dpgt_CombineGVCFsOnSites */

#ifndef _Included_org_bgi_flexlab_dpgt_CombineGVCFsOnSites
#define _Included_org_bgi_flexlab_dpgt_CombineGVCFsOnSites
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bgi_flexlab_dpgt_CombineGVCFsOnSites
 * Method:    Combine
 * Signature: ([Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[BLjava/lang/String;JJ)V
 */
JNIEXPORT void JNICALL Java_org_bgi_flexlab_dpgt_CombineGVCFsOnSites_Combine
  (JNIEnv *, jobject, jobjectArray, jstring, jstring, jbyteArray, jstring, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
