/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bgi_flexlab_dpgt_jointcalling_NativeInitializer */

#ifndef _Included_org_bgi_flexlab_dpgt_jointcalling_NativeInitializer
#define _Included_org_bgi_flexlab_dpgt_jointcalling_NativeInitializer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bgi_flexlab_dpgt_jointcalling_NativeInitializer
 * Method:    apply
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_bgi_flexlab_dpgt_jointcalling_NativeInitializer_apply
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
