/**
This file is part of DPGT.
Copyright (C) 2022 BGI.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
// License End
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bgi_flexlab_dpgt_jointcalling_NativeInitializer */

#ifndef _Included_org_bgi_flexlab_dpgt_jointcalling_NativeInitializer
#define _Included_org_bgi_flexlab_dpgt_jointcalling_NativeInitializer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bgi_flexlab_dpgt_jointcalling_NativeInitializer
 * Method:    apply
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_bgi_flexlab_dpgt_jointcalling_NativeInitializer_apply
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
