/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bgi_flexlab_dpgt_utils_NativeResponse */

#ifndef _Included_org_bgi_flexlab_dpgt_utils_NativeResponse
#define _Included_org_bgi_flexlab_dpgt_utils_NativeResponse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bgi_flexlab_dpgt_utils_NativeResponse
 * Method:    apply
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_bgi_flexlab_dpgt_utils_NativeResponse_apply
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
