/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bgi_flexlab_dpgt_jointcalling_VCFHeaderCombiner */

#ifndef _Included_org_bgi_flexlab_dpgt_jointcalling_VCFHeaderCombiner
#define _Included_org_bgi_flexlab_dpgt_jointcalling_VCFHeaderCombiner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bgi_flexlab_dpgt_jointcalling_VCFHeaderCombiner
 * Method:    Combine
 * Signature: ([Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_bgi_flexlab_dpgt_jointcalling_VCFHeaderCombiner_Combine
  (JNIEnv *, jobject, jobjectArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
